[package]
name = "fsr2_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { path = "../wgpu/wgpu" }
wgpu-core = { path = "../wgpu/wgpu-core" }
wgpu-hal = { path = "../wgpu/wgpu-hal" }
ash = "0.37"
glam = "0.22"
bitflags = "1.3"

[build-dependencies]
bindgen = "0.63"
